### ISSUE TITLE
Uso talvez desnecessário de `useCallback`

### ISSUE THREAD

**Issue by xfer** [wilsonfaustino/Desafio01-Todo#5]
Se o componente não usa um `useMemo`, normalmente esse `useCallback` vai piorar um pouco performance do app e reduzir legibilidade. 

https://github.com/wilsonfaustino/Desafio01-Todo/blob/87d00034053081d09ebe0659d822af75ac51ec9b/src/App.tsx#L15

**Comment by wilsonfaustino** [comment]
🤔 interessante.. removido
