### ISSUE TITLE
Comentários desnecessários

### ISSUE THREAD

**Issue by xfer** [wilsonfaustino/Desafio01-Todo#6]
https://github.com/wilsonfaustino/Desafio01-Todo/blob/87d00034053081d09ebe0659d822af75ac51ec9b/src/App.tsx#L3

https://github.com/wilsonfaustino/Desafio01-Todo/blob/87d00034053081d09ebe0659d822af75ac51ec9b/src/App.tsx#L6

https://github.com/wilsonfaustino/Desafio01-Todo/blob/87d00034053081d09ebe0659d822af75ac51ec9b/src/App.tsx#L13-L14

https://github.com/wilsonfaustino/Desafio01-Todo/blob/87d00034053081d09ebe0659d822af75ac51ec9b/src/App.tsx#L36-L37

**Comment by wilsonfaustino** [comment]
encarnei o capitão óbvio
