### ISSUE TITLE
Sem medida

### ISSUE THREAD

**Issue by xfer** [wilsonfaustino/Desafio01-Todo#9]
https://github.com/wilsonfaustino/Desafio01-Todo/blob/87d00034053081d09ebe0659d822af75ac51ec9b/src/components/EmptyList.module.css#L15

**Comment by wilsonfaustino** [comment]
uai..  esse eu segui como mostrado no MDN

![image](https://user-images.githubusercontent.com/25889686/175830801-e5dcbd7f-83c9-46cb-acf2-185e0a213546.png)

**Comment by xfer** [comment]
ah, exceto pra 0 e escala, o resto eu acho que tem que ter medida, sei lá. Mas também é pq eu uso mais _shorthand notation_
